return function(colors, options)
  local normal_bg = options.transparent and colors.none or colors.bg
  local alt_bg = options.transparent and colors.none or colors.bg_alt
  local float_bg = options.transparent and colors.none or colors.float
  local cursor_bg = options.transparent and colors.none or colors.cursorline

  return {
    ColorColumn = { bg = alt_bg },
    Conceal = { fg = colors.comment },
    Cursor = { reverse = true },
    CursorColumn = { bg = cursor_bg },
    CursorIM = { link = 'Cursor' },
    CursorLine = { bg = cursor_bg },
    CursorLineNr = { fg = colors.accent, bg = cursor_bg, bold = true },
    DiffAdd = { fg = colors.diff.add, bg = colors.diff.add_bg },
    DiffChange = { fg = colors.diff.change, bg = colors.diff.change_bg },
    DiffDelete = { fg = colors.diff.delete, bg = colors.diff.delete_bg },
    DiffText = { bg = colors.diff.text_bg, bold = true },
    Directory = { fg = colors.syntax.namespace, bold = true },
    EndOfBuffer = { fg = colors.nontext },
    ErrorMsg = { fg = colors.diag.error, bold = true },
    FloatBorder = { fg = colors.border, bg = float_bg },
    FloatTitle = { fg = colors.syntax.title, bg = float_bg, bold = true },
    FoldColumn = { fg = colors.gutter, bg = normal_bg },
    Folded = { fg = colors.comment, bg = alt_bg, italic = true },
    IncSearch = { fg = colors.bg, bg = colors.syntax.constant, bold = true },
    LineNr = { fg = colors.gutter, bg = normal_bg },
    MatchParen = { fg = colors.syntax.namespace, bg = colors.match, bold = true },
    ModeMsg = { fg = colors.syntax.title, bold = true },
    MoreMsg = { fg = colors.diag.ok, bold = true },
    NonText = { fg = colors.nontext },
    Normal = { fg = colors.fg, bg = normal_bg },
    NormalFloat = { fg = colors.fg, bg = float_bg },
    NormalNC = { fg = colors.fg, bg = normal_bg },
    Pmenu = { fg = colors.fg, bg = alt_bg },
    PmenuSbar = { bg = colors.subtle },
    PmenuSel = { fg = colors.bg, bg = colors.accent, bold = true },
    PmenuThumb = { bg = colors.comment },
    Question = { fg = colors.diag.info, bold = true },
    QuickFixLine = { bg = colors.match, bold = true },
    Search = { fg = colors.fg, bg = colors.search },
    SignColumn = { fg = colors.gutter, bg = normal_bg },
    SpecialKey = { fg = colors.nontext },
    SpellBad = { undercurl = true, sp = colors.diag.error },
    SpellCap = { undercurl = true, sp = colors.diag.info },
    SpellLocal = { undercurl = true, sp = colors.diag.hint },
    SpellRare = { undercurl = true, sp = colors.diag.warn },
    StatusLine = { fg = colors.fg, bg = alt_bg },
    StatusLineNC = { fg = colors.comment, bg = alt_bg },
    Substitute = { fg = colors.bg, bg = colors.syntax.constant, bold = true },
    TabLine = { fg = colors.comment, bg = alt_bg },
    TabLineFill = { bg = alt_bg },
    TabLineSel = { fg = colors.fg, bg = normal_bg, bold = true },
    TermCursor = { reverse = true },
    TermCursorNC = { fg = colors.bg, bg = colors.comment },
    Title = { fg = colors.syntax.title, bold = true },
    VertSplit = { link = 'WinSeparator' },
    Visual = { bg = colors.visual },
    VisualNOS = { link = 'Visual' },
    WarningMsg = { fg = colors.diag.warn, bold = true },
    Whitespace = { fg = colors.nontext },
    WildMenu = { link = 'PmenuSel' },
    WinBar = { fg = colors.fg, bg = normal_bg, bold = true },
    WinBarNC = { fg = colors.comment, bg = normal_bg },
    WinSeparator = { fg = colors.border, bg = normal_bg },
  }
end
