return function(colors, options)
  local normal_bg = options.transparent and colors.none or colors.bg

  return {
    DiagnosticError = { fg = colors.diag.error },
    DiagnosticFloatingError = { link = 'DiagnosticError' },
    DiagnosticFloatingHint = { link = 'DiagnosticHint' },
    DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
    DiagnosticFloatingOk = { link = 'DiagnosticOk' },
    DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
    DiagnosticHint = { fg = colors.diag.hint },
    DiagnosticInfo = { fg = colors.diag.info },
    DiagnosticOk = { fg = colors.diag.ok },
    DiagnosticSignError = { fg = colors.diag.error, bg = normal_bg },
    DiagnosticSignHint = { fg = colors.diag.hint, bg = normal_bg },
    DiagnosticSignInfo = { fg = colors.diag.info, bg = normal_bg },
    DiagnosticSignOk = { fg = colors.diag.ok, bg = normal_bg },
    DiagnosticSignWarn = { fg = colors.diag.warn, bg = normal_bg },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.diag.error },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.diag.hint },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.diag.info },
    DiagnosticUnderlineOk = { undercurl = true, sp = colors.diag.ok },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.diag.warn },
    DiagnosticVirtualTextError = { fg = colors.diag.error, bg = colors.diag.error_bg },
    DiagnosticVirtualTextHint = { fg = colors.diag.hint, bg = colors.diag.hint_bg },
    DiagnosticVirtualTextInfo = { fg = colors.diag.info, bg = colors.diag.info_bg },
    DiagnosticVirtualTextOk = { fg = colors.diag.ok, bg = colors.diag.ok_bg },
    DiagnosticVirtualTextWarn = { fg = colors.diag.warn, bg = colors.diag.warn_bg },
    DiagnosticWarn = { fg = colors.diag.warn },
    LspCodeLens = { fg = colors.comment, italic = true },
    LspInlayHint = { fg = colors.comment, bg = colors.subtle },
    LspReferenceText = { bg = colors.match },
    LspReferenceRead = { link = 'LspReferenceText' },
    LspReferenceWrite = { bg = colors.match, underline = true },
    LspSignatureActiveParameter = { bg = colors.match, bold = true },
    ['@lsp.mod.defaultLibrary'] = { link = '@variable.builtin' },
    ['@lsp.type.boolean'] = { link = '@boolean' },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.comment'] = { link = '@comment' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.macro'] = { link = '@function.macro' },
    ['@lsp.type.method'] = { link = '@function.method' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.type.parameter'] = { link = '@variable.parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type.definition' },
    ['@lsp.type.variable'] = { link = '@variable' },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
    ['@lsp.typemod.variable.static'] = { link = '@constant' },
  }
end
