local util = require('solarized.util')

return function(colors, options)
  local styles = options.styles

  return {
    ['@attribute'] = { fg = colors.syntax.attribute },
    ['@boolean'] = { fg = colors.syntax.boolean },
    ['@character'] = { fg = colors.syntax.character },
    ['@character.special'] = { fg = colors.syntax.special },
    ['@comment'] = util.extend({ fg = colors.syntax.comment }, styles.comments),
    ['@comment.documentation'] = util.extend({ fg = colors.comment }, styles.comments),
    ['@comment.error'] = { fg = colors.bg, bg = colors.diag.error, bold = true },
    ['@comment.note'] = { fg = colors.bg, bg = colors.diag.hint, bold = true },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.warning'] = { fg = colors.bg, bg = colors.diag.warn, bold = true },
    ['@constant'] = { fg = colors.syntax.constant },
    ['@constant.builtin'] = { fg = colors.syntax.builtin },
    ['@constructor'] = util.extend({ fg = colors.syntax.type }, styles.types),
    ['@diff.delta'] = { fg = colors.diff.change },
    ['@diff.minus'] = { fg = colors.diff.delete },
    ['@diff.plus'] = { fg = colors.diff.add },
    ['@field'] = { link = '@variable.member' },
    ['@function'] = util.extend({ fg = colors.syntax.function_name }, styles.functions),
    ['@function.builtin'] = { fg = colors.syntax.builtin },
    ['@function.call'] = util.extend({ fg = colors.syntax.function_name }, styles.functions),
    ['@function.macro'] = { fg = colors.syntax.preproc },
    ['@function.method'] = util.extend({ fg = colors.syntax.method }, styles.functions),
    ['@function.method.call'] = { link = '@function.method' },
    ['@keyword'] = util.extend({ fg = colors.syntax.keyword }, styles.keywords),
    ['@keyword.conditional'] = util.extend({ fg = colors.syntax.keyword }, styles.keywords),
    ['@keyword.exception'] = util.extend({ fg = colors.syntax.keyword }, styles.keywords),
    ['@keyword.function'] = util.extend({ fg = colors.syntax.keyword }, styles.keywords),
    ['@keyword.operator'] = util.extend({ fg = colors.syntax.operator }, styles.keywords),
    ['@keyword.return'] = util.extend({ fg = colors.syntax.keyword }, styles.keywords),
    ['@markup.heading'] = { fg = colors.syntax.title, bold = true },
    ['@markup.heading.1'] = { fg = colors.syntax.title, bold = true },
    ['@markup.heading.2'] = { fg = colors.syntax.attribute, bold = true },
    ['@markup.link'] = { fg = colors.syntax.uri, underline = true },
    ['@markup.link.label'] = { fg = colors.syntax.attribute },
    ['@markup.link.url'] = { fg = colors.syntax.uri, underline = true },
    ['@markup.list'] = { fg = colors.syntax.keyword },
    ['@markup.raw'] = { fg = colors.syntax.special },
    ['@method'] = { link = '@function.method' },
    ['@method.call'] = { link = '@function.method.call' },
    ['@module'] = { fg = colors.syntax.namespace },
    ['@namespace'] = { fg = colors.syntax.namespace },
    ['@number'] = { fg = colors.syntax.number },
    ['@operator'] = { fg = colors.syntax.operator },
    ['@parameter'] = { link = '@variable.parameter' },
    ['@property'] = { fg = colors.syntax.property },
    ['@punctuation.bracket'] = { fg = colors.syntax.punctuation },
    ['@punctuation.delimiter'] = { fg = colors.syntax.punctuation },
    ['@punctuation.special'] = { fg = colors.syntax.special },
    ['@string'] = { fg = colors.syntax.string },
    ['@string.escape'] = { fg = colors.syntax.special },
    ['@string.regexp'] = { fg = colors.syntax.special },
    ['@tag'] = { fg = colors.syntax.tag },
    ['@tag.attribute'] = { fg = colors.syntax.attribute },
    ['@tag.delimiter'] = { fg = colors.syntax.punctuation },
    ['@type'] = util.extend({ fg = colors.syntax.type }, styles.types),
    ['@type.builtin'] = util.extend({ fg = colors.syntax.type }, styles.types),
    ['@type.definition'] = util.extend({ fg = colors.syntax.type }, styles.types),
    ['@variable'] = util.extend({ fg = colors.syntax.variable }, styles.variables),
    ['@variable.builtin'] = { fg = colors.syntax.builtin },
    ['@variable.parameter'] = { fg = colors.syntax.parameter },
    ['@variable.parameter.builtin'] = { fg = colors.syntax.builtin },
    ['@variable.member'] = { fg = colors.syntax.property },
  }
end
