return function(colors, _options)
  return {
    BlinkCmpDoc = { link = 'NormalFloat' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpDocCursorLine = { link = 'Visual' },
    BlinkCmpGhostText = { fg = colors.comment },
    BlinkCmpKind = { fg = colors.comment },
    BlinkCmpKindClass = { link = 'Type' },
    BlinkCmpKindCodeium = { link = 'String' },
    BlinkCmpKindConstant = { link = 'Constant' },
    BlinkCmpKindConstructor = { link = '@constructor' },
    BlinkCmpKindCopilot = { link = 'String' },
    BlinkCmpKindDefault = { fg = colors.comment },
    BlinkCmpKindEnum = { link = 'Type' },
    BlinkCmpKindEnumMember = { link = 'Constant' },
    BlinkCmpKindEvent = { link = 'Type' },
    BlinkCmpKindField = { link = '@variable.member' },
    BlinkCmpKindFile = { link = 'Directory' },
    BlinkCmpKindFolder = { link = 'Directory' },
    BlinkCmpKindFunction = { link = 'Function' },
    BlinkCmpKindInterface = { link = 'Type' },
    BlinkCmpKindKeyword = { link = 'Keyword' },
    BlinkCmpKindMethod = { link = '@function.method' },
    BlinkCmpKindModule = { link = '@module' },
    BlinkCmpKindOperator = { link = 'Operator' },
    BlinkCmpKindProperty = { link = '@property' },
    BlinkCmpKindReference = { link = 'Special' },
    BlinkCmpKindSnippet = { link = 'Special' },
    BlinkCmpKindStruct = { link = 'Type' },
    BlinkCmpKindSupermaven = { link = 'String' },
    BlinkCmpKindTabNine = { link = 'String' },
    BlinkCmpKindText = { fg = colors.fg },
    BlinkCmpKindTypeParameter = { link = 'Type' },
    BlinkCmpKindUnit = { link = 'Number' },
    BlinkCmpKindValue = { link = 'String' },
    BlinkCmpKindVariable = { link = '@variable' },
    BlinkCmpLabel = { fg = colors.fg },
    BlinkCmpLabelDeprecated = { fg = colors.comment, strikethrough = true },
    BlinkCmpLabelDetails = { fg = colors.comment },
    BlinkCmpLabelMatch = { fg = colors.syntax.function_name, bold = true },
    BlinkCmpMenu = { link = 'Pmenu' },
    BlinkCmpMenuBorder = { link = 'FloatBorder' },
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
    BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
    BlinkCmpSignatureHelp = { link = 'NormalFloat' },
    BlinkCmpSignatureHelpActiveParameter = { link = 'LspSignatureActiveParameter' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
  }
end
