return function(colors, _options)
  return {
    CmpDocumentation = { link = 'NormalFloat' },
    CmpDocumentationBorder = { link = 'FloatBorder' },
    CmpGhostText = { fg = colors.comment },
    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.syntax.function_name, bold = true },
    CmpItemAbbrMatchFuzzy = { link = 'CmpItemAbbrMatch' },
    CmpItemKind = { fg = colors.syntax.type },
    CmpItemKindClass = { link = 'Type' },
    CmpItemKindCodeium = { link = 'String' },
    CmpItemKindConstant = { link = 'Constant' },
    CmpItemKindConstructor = { link = '@constructor' },
    CmpItemKindCopilot = { link = 'String' },
    CmpItemKindDefault = { fg = colors.comment },
    CmpItemKindEnum = { link = 'Type' },
    CmpItemKindEnumMember = { link = 'Constant' },
    CmpItemKindEvent = { link = 'Type' },
    CmpItemKindField = { link = '@variable.member' },
    CmpItemKindFile = { link = 'Directory' },
    CmpItemKindFolder = { link = 'Directory' },
    CmpItemKindFunction = { link = 'Function' },
    CmpItemKindInterface = { link = 'Type' },
    CmpItemKindKeyword = { link = 'Keyword' },
    CmpItemKindMethod = { link = '@function.method' },
    CmpItemKindModule = { link = '@module' },
    CmpItemKindOperator = { link = 'Operator' },
    CmpItemKindProperty = { link = '@property' },
    CmpItemKindReference = { link = 'Special' },
    CmpItemKindSnippet = { link = 'Special' },
    CmpItemKindStruct = { link = 'Type' },
    CmpItemKindSupermaven = { link = 'String' },
    CmpItemKindTabNine = { link = 'String' },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindTypeParameter = { link = 'Type' },
    CmpItemKindUnit = { link = 'Number' },
    CmpItemKindValue = { link = 'String' },
    CmpItemKindVariable = { link = '@variable' },
    CmpItemMenu = { fg = colors.comment },
  }
end
